<a href="https://colab.research.google.com/github/mohammadzainabbas/Channel_Logo_Detection/blob/master/Test.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
import numpy as np, cv2 as cv

np.set_printoptions(precision=2, suppress=True, linewidth=150)

In [0]:
row, col = 100, 200
a = np.random.rand(row, col)
print(a)

[[0.81 0.51 0.46 ... 0.52 0.54 0.02]
 [0.71 0.79 0.24 ... 0.42 0.12 0.35]
 [0.74 0.19 0.56 ... 0.16 0.42 0.6 ]
 ...
 [0.69 0.19 0.75 ... 0.73 0.1  0.89]
 [0.58 0.75 0.6  ... 0.48 0.62 0.54]
 [0.45 0.9  0.59 ... 0.72 0.99 0.36]]


In [0]:
np.shape(a)[1]*.4

80.0

In [0]:
row_th, col_th = .4, .3
a1 = a[:int(np.shape(a)[0]*row_th), :int(np.shape(a)[1]*col_th)]
a2 = a[-int(np.shape(a)[0]*row_th):, :int(np.shape(a)[1]*col_th)]
a3 = a[:int(np.shape(a)[0]*row_th), -int(np.shape(a)[1]*col_th):]
a4 = a[-int(np.shape(a)[0]*row_th):, -int(np.shape(a)[1]*col_th):]


In [0]:
print(a1)

[[0.81 0.51 0.46 ... 0.36 0.85 0.89]
 [0.71 0.79 0.24 ... 0.49 0.77 0.19]
 [0.74 0.19 0.56 ... 0.23 0.27 0.92]
 ...
 [0.21 0.26 0.69 ... 0.92 0.96 0.32]
 [0.55 0.37 0.77 ... 0.92 0.56 0.86]
 [0.93 0.88 0.21 ... 0.16 0.23 0.5 ]]


In [0]:
print(a2)

[[0.62 0.15 0.06 ... 0.97 0.2  0.64]
 [0.53 0.17 0.71 ... 0.86 0.45 0.54]
 [0.37 0.21 0.58 ... 0.86 0.11 0.83]
 ...
 [0.69 0.19 0.75 ... 0.19 0.77 0.73]
 [0.58 0.75 0.6  ... 0.51 0.48 0.91]
 [0.45 0.9  0.59 ... 0.36 0.46 0.65]]


In [0]:
print(a3)

[[0.83 0.39 0.56 ... 0.52 0.54 0.02]
 [0.03 0.27 0.89 ... 0.42 0.12 0.35]
 [0.16 0.35 0.47 ... 0.16 0.42 0.6 ]
 ...
 [0.87 0.06 0.6  ... 0.88 0.52 0.84]
 [0.32 0.38 0.34 ... 0.14 0.71 0.73]
 [0.95 0.01 0.32 ... 0.85 0.65 0.02]]


In [0]:
print(a4)

[[0.2  0.66 0.17 ... 0.86 0.61 0.46]
 [0.38 0.4  0.98 ... 0.47 0.4  0.39]
 [0.99 0.43 1.   ... 0.27 0.85 0.47]
 ...
 [0.79 0.47 0.85 ... 0.73 0.1  0.89]
 [0.11 0.74 0.5  ... 0.48 0.62 0.54]
 [0.31 0.94 0.3  ... 0.72 0.99 0.36]]


In [0]:
np.shape(a), np.shape(a1), np.shape(a2), np.shape(a3), np.shape(a4)

((100, 200), (40, 60), (40, 60), (40, 60), (40, 60))

In [74]:
import os
img_list = os.listdir("geo_image")
len(img_list)

1801

In [76]:
'geo_image/' + img_list[1]

'geo_image/frame119.jpg'

In [0]:
a = np.array(cv.imread('geo_image/' + img_list[1],cv.IMREAD_COLOR))

In [0]:
row_th, col_th = .35, .35
a1 = a[:int(np.shape(a)[0]*row_th), :int(np.shape(a)[1]*col_th)]
a2 = a[-int(np.shape(a)[0]*row_th):, :int(np.shape(a)[1]*col_th)]
a3 = a[:int(np.shape(a)[0]*row_th), -int(np.shape(a)[1]*col_th):]
a4 = a[-int(np.shape(a)[0]*row_th):, -int(np.shape(a)[1]*col_th):]

In [79]:
cv.imwrite('t/Top Left.png',a1)
cv.imwrite('t/Top Right.png',a3)
cv.imwrite('t/Bottom Left.png',a2)
cv.imwrite('t/Bottom Right.png',a4)

True

In [0]:
a[:int(np.shape(a)[0]*row_th), :int(np.shape(a)[1]*col_th)] = 0
a[-int(np.shape(a)[0]*row_th):, :int(np.shape(a)[1]*col_th)] = 0
a[:int(np.shape(a)[0]*row_th), -int(np.shape(a)[1]*col_th):] = 0
a[-int(np.shape(a)[0]*row_th):, -int(np.shape(a)[1]*col_th):] = 0

In [81]:
cv.imwrite('t/New Image.png',a)

True

In [47]:
import os

# set video file path of input video with name and extension
vid = cv.VideoCapture('test.mp4')


if not os.path.exists('image'):
    os.makedirs('image')

#for frame identity
index = 0
while(True):
    # Extract images
    ret, frame = vid.read()
    # end of frames
    if not ret: 
        break
    # Saves images
    name = './image/frame' + str(index) + '.jpg'
    print ('Creating...' + name)
    cv.imwrite(name, frame)

    # next frame
    index += 1

Creating..../image/frame0.jpg
Creating..../image/frame1.jpg
Creating..../image/frame2.jpg
Creating..../image/frame3.jpg
Creating..../image/frame4.jpg
Creating..../image/frame5.jpg
Creating..../image/frame6.jpg
Creating..../image/frame7.jpg
Creating..../image/frame8.jpg
Creating..../image/frame9.jpg
Creating..../image/frame10.jpg
Creating..../image/frame11.jpg
Creating..../image/frame12.jpg
Creating..../image/frame13.jpg
Creating..../image/frame14.jpg
Creating..../image/frame15.jpg
Creating..../image/frame16.jpg
Creating..../image/frame17.jpg
Creating..../image/frame18.jpg
Creating..../image/frame19.jpg
Creating..../image/frame20.jpg
Creating..../image/frame21.jpg
Creating..../image/frame22.jpg
Creating..../image/frame23.jpg
Creating..../image/frame24.jpg
Creating..../image/frame25.jpg
Creating..../image/frame26.jpg
Creating..../image/frame27.jpg
Creating..../image/frame28.jpg
Creating..../image/frame29.jpg
Creating..../image/frame30.jpg
Creating..../image/frame31.jpg
Creating..../image

In [48]:
vid.get(cv.cv2.CAP_PROP_FPS)

23.976023976023978

In [49]:
vid.get(cv.cv2.CAP_PROP_FRAME_COUNT)

576.0

In [50]:
vid.get(cv.cv2.CAP_PROP_FRAME_COUNT) / vid.get(cv.cv2.CAP_PROP_FPS)

24.023999999999997

In [32]:
!curl -L https://yt-dl.org/downloads/latest/youtube-dl -o /usr/local/bin/youtube-dl

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     3    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
  0     3    0     0    0     0      0      0 --:--:--  0:00:01 --:--:--     0
100   599    0   599    0     0    316      0 --:--:--  0:00:01 --:--:--  4572
100 1679k  100 1679k    0     0   418k      0  0:00:04  0:00:04 --:--:-- 1194k


In [40]:
!youtube-dl 'https://www.youtube.com/watch?v=Cn5l7HJaYuA' -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

[youtube] Cn5l7HJaYuA: Downloading webpage
[youtube] Cn5l7HJaYuA: Downloading video info webpage
[download] Destination: 'Piper' Clip - Finding Dory - In Theatres this Friday!-Cn5l7HJaYuA.f137.mp4
[download] 100% of 6.93MiB in 00:00
[download] Destination: 'Piper' Clip - Finding Dory - In Theatres this Friday!-Cn5l7HJaYuA.f140.m4a
[download] 100% of 381.30KiB in 00:00
[ffmpeg] Merging formats into "'Piper' Clip - Finding Dory - In Theatres this Friday!-Cn5l7HJaYuA.mp4"
Deleting original file 'Piper' Clip - Finding Dory - In Theatres this Friday!-Cn5l7HJaYuA.f137.mp4 (pass -k to keep)
Deleting original file 'Piper' Clip - Finding Dory - In Theatres this Friday!-Cn5l7HJaYuA.f140.m4a (pass -k to keep)


In [51]:
!youtube-dl Cn5l7HJaYuA -o 't/test.mp4' -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/best[ext=mp4]/best'

[youtube] Cn5l7HJaYuA: Downloading webpage
[youtube] Cn5l7HJaYuA: Downloading video info webpage
[download] Destination: t/test.f137.mp4
[download] 100% of 6.93MiB in 00:00
[download] Destination: t/test.mp4.f140
[download] 100% of 381.30KiB in 00:00
[ffmpeg] Merging formats into "t/test.mp4"
Deleting original file t/test.f137.mp4 (pass -k to keep)
Deleting original file t/test.mp4.f140 (pass -k to keep)
